/**
 * Single import surface for content types used across the app.
 *
 * The **source of truth** is `./sanity.types.ts`, generated by Sanity TypeGen
 * from the schema + the GROQ queries (`pnpm typegen`). This file only *adapts*
 * those generated query-result types into friendly names and element types —
 * it defines no content shape of its own, so there is no second source of
 * truth (Sprint 0.1 §5).
 *
 * The only hand-written types here are two structural helpers that are not
 * schema entities: `PortableText` (a render input) and `SanityImage` (a
 * permissive shape accepted by `@sanity/image-url`).
 */
import type {
  ProfileQueryResult,
  Project,
  ProjectBySlugQueryResult,
  ProjectsListQueryResult,
  SiteSettingsQueryResult,
} from "./sanity.types";

// -- structural helpers (not schema contracts) ----------------------------

/** Portable Text value handed to `@portabletext/react`. */
export type PortableText = Array<Record<string, unknown>>;

/** Minimal image shape; `@sanity/image-url` only needs `asset._ref`. */
export interface SanityImage {
  _type?: string;
  asset?: { _ref?: string; _type?: string; [key: string]: unknown };
  alt?: string;
  caption?: string;
  hotspot?: unknown;
  crop?: unknown;
  [key: string]: unknown;
}

// -- query results ------------------------------------------------------

export type ProjectListItem = NonNullable<ProjectsListQueryResult[number]>;
export type ProjectDetail = NonNullable<ProjectBySlugQueryResult>;
export type Profile = NonNullable<ProfileQueryResult>;
export type SiteSettings = NonNullable<SiteSettingsQueryResult>;

// -- derived element / field types -----------------------------------

export type ProjectType = NonNullable<ProjectListItem["projectType"]>;
export type ProjectVisibility = NonNullable<ProjectListItem["visibility"]>;
export type ProjectStatus = NonNullable<Project["status"]>;

export type Contribution = NonNullable<ProjectListItem["contribution"]>;
export type Authorship = NonNullable<Contribution["authorship"]>;
export type DateRange = NonNullable<ProjectListItem["period"]>;

export type TechnologyRef = NonNullable<
  ProjectListItem["technologies"]
>[number];
export type SkillRef = NonNullable<ProjectDetail["skills"]>[number];
export type ExperienceRef = NonNullable<ProjectDetail["relatedExperience"]>;
export type EducationRef = NonNullable<ProjectDetail["relatedEducation"]>;

export type ExternalLink = NonNullable<ProjectDetail["links"]>[number];
export type Evidence = NonNullable<ProjectDetail["evidence"]>[number];
export type Metric = NonNullable<ProjectDetail["metrics"]>[number];
export type Seo = NonNullable<ProjectDetail["seo"]>;

// -- content blocks --------------------------------------------------

/** The closed union of blocks the CMS can emit (schema-constrained). */
export type ContentBlock = NonNullable<ProjectDetail["contentBlocks"]>[number];
export type KnownContentBlock = ContentBlock;

/** Runtime guard shape for a block whose `_type` has no renderer (deploy skew). */
export type UnknownContentBlock = {
  _key: string;
  _type: string;
  [key: string]: unknown;
};
export type AnyContentBlock = ContentBlock | UnknownContentBlock;

type BlockOfType<T extends ContentBlock["_type"]> = Extract<
  ContentBlock,
  { _type: T }
>;

export type RichTextBlock = BlockOfType<"richTextBlock">;
export type ImageBlock = BlockOfType<"imageBlock">;
export type GalleryBlock = BlockOfType<"galleryBlock">;
export type VideoBlock = BlockOfType<"videoBlock">;
export type MetricGridBlock = BlockOfType<"metricGridBlock">;
export type BeforeAfterBlock = BlockOfType<"beforeAfterBlock">;
export type ArchitectureBlock = BlockOfType<"architectureBlock">;
export type TimelineBlock = BlockOfType<"timelineBlock">;
export type TechnicalDecisionsBlock = BlockOfType<"technicalDecisionsBlock">;
export type LearningBlock = BlockOfType<"learningBlock">;
export type CalloutBlock = BlockOfType<"calloutBlock">;
export type LinksBlock = BlockOfType<"linksBlock">;
